### ISSUE TITLE
siacoin wallet issue

### ISSUE THREAD

**Issue by savaliyahitesh** [NebulousLabs/Sia-Support-Docs#5]
my sia wallet is not open last 7 days, i enter my password correctly but the wallet does not open and there shown password is incorrect, so i started the process of restoring of my wallet through my seed after all password shown incorrect so what can i do? plz help me

**Comment by dghelm** [comment]
This isn't the best place to find active support. Please join the Discord and there will be plenty of folks that can point you to answers. [https://discord.com/invite/sia](https://discord.com/invite/sia)
